### ISSUE TITLE
data

### ISSUE THREAD

**Issue by caiyingchun** [episodeyang/grammar_variational_autoencoder#2]
Could you please send me a copy of eq2_grammar_dataset.h5 and eq2_str_dataset.h5? I can't access the raw data at all. My email is cai_yingchun@hotmail.com. Thank you very much!!!

**Comment by geyang** [comment]
Just added the data files as fc4144b9ab5db8fa8780be6bbb1dfbc6a7dcc1c6

The files are 300 MB big, good luck downloading them :P
